kind: Service
apiVersion: v1
metadata:
  name: prometheus-openshift-streams
  labels:
    app: prometheus-openshift-streams
spec:
  ports:
    - name: web
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    prometheus: prometheus-openshift-streams
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
